using System.Text;

namespace SAS.DialogueSystem.EditorTools
{
    internal static class DialogueInkBuilder
    {
        public static string Build(DialogueStoryDraft draft)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// Generated by Dialogue Story Writer.");
            builder.AppendLine("// Edit the DialogueStoryDraft asset when possible.");

            if (draft.includeCommonInk)
                WriteIncludes(builder, draft);

            WriteGlobalTags(builder, draft);

            if (draft.writeStartDivert && TryGetStartKnot(draft, out var startKnot))
            {
                builder.AppendLine();
                builder.AppendLine($"-> {InkSanitizer.SanitizeDivertTarget(startKnot)}");
            }

            foreach (var section in draft.sections)
            {
                builder.AppendLine();
                builder.AppendLine(InkEntryWriter.BuildSectionHeader(section));

                var wroteTerminal = false;
                foreach (var entry in section.entries)
                {
                    InkEntryWriter.WriteEntry(builder, entry);
                    if (InkEntryWriter.IsTerminalEntry(entry))
                        wroteTerminal = true;
                }

                if (section.sectionType != DialogueStorySectionType.Function &&
                    !wroteTerminal &&
                    draft.appendEndToLineOnlySections)
                {
                    builder.AppendLine("-> END");
                }
            }

            return builder.ToString();
        }

        private static void WriteGlobalTags(StringBuilder builder, DialogueStoryDraft draft)
        {
            if (draft.globalTags == null)
                return;

            foreach (var tag in draft.globalTags)
            {
                var tagLine = InkTagWriter.BuildCustomTagLine(tag);
                if (!string.IsNullOrWhiteSpace(tagLine))
                    builder.AppendLine(tagLine);
            }
        }

        private static void WriteIncludes(StringBuilder builder, DialogueStoryDraft draft)
        {
            var wroteInclude = false;
            if (draft.includeFiles != null)
            {
                foreach (var includeFile in draft.includeFiles)
                {
                    if (string.IsNullOrWhiteSpace(includeFile))
                        continue;

                    builder.AppendLine($"INCLUDE {InkSanitizer.CleanSingleLine(includeFile)}");
                    wroteInclude = true;
                }
            }

            if (!wroteInclude && !string.IsNullOrWhiteSpace(draft.commonInkFile))
                builder.AppendLine($"INCLUDE {InkSanitizer.CleanSingleLine(draft.commonInkFile)}");
        }

        private static bool TryGetStartKnot(DialogueStoryDraft draft, out string startKnot)
        {
            startKnot = string.Empty;
            if (draft == null)
                return false;

            if (!string.IsNullOrWhiteSpace(draft.startKnot))
            {
                startKnot = draft.startKnot;
                return true;
            }

            if (draft.sections == null)
                return false;

            foreach (var section in draft.sections)
            {
                if (section == null || string.IsNullOrWhiteSpace(section.knotName))
                    continue;

                startKnot = section.knotName;
                return true;
            }

            return false;
        }
    }
}
